name: Deploy website

on:
  push:
    branches:
      - draft # will be changed later

jobs:
  invoke-webhook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Invoke Webhook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        curl $WEBHOOK_URL
